### ISSUE TITLE
Compatibility with Facebook's new site

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#103]
Facebook is rolling out a new frontend at some point soon. Most likely this will break certain parts of the tool, which will need to be rewritten to work with the new site, or some way to force the use of the existing mobile version of the site.

**Comment by fmjensen** [comment]
I think the new Activitylog contains functionality that could be beneficial for you to look at ;-)

**Comment by weskerfoot** [comment]
related https://github.com/weskerfoot/DeleteFB/issues/128#issuecomment-678833971

**Comment by weskerfoot** [comment]
> I think the new Activitylog contains functionality that could be beneficial for you to look at ;-)

yes, looks like it works with `mobile.facebook.com` which is useful
