### ISSUE TITLE
No Action after setup and Launch

### ISSUE THREAD

**Issue by enemymind** [weskerfoot/DeleteFB#107]
Hello, 

Just wondering if this is still in working order, after some troubleshooting I got this working on my mac, it pops open chrome, everything seems good.... and it just sits there and does not appear to do anything. 

Perhaps I am missing something or has a recent FB update made this inoperable?.

**Comment by weskerfoot** [comment]
@enemymind that may well be, can you share a screenshot? Facebook is rolling out updates that might have broken this

**Comment by weskerfoot** [comment]
Also, any error messages or anything in the console? It won't close chrome if there is an error.

**Comment by enemymind** [comment]
I can recreate if you would like, but it simply launched the browser, entered the l/p and 2fa code. Logs in and then the browser just sits. 

Terminal also just pauses. 

No messages, is there a log file somewhere I can pull?

**Comment by weskerfoot** [comment]
@enemymind I'm not able to reproduce, but it might be related to the specific version of Chrome you have installed.

Could you tell me what version of Chrome (or Chromium) you have? Also what OS, and if possible, which version of the selenium Chromedriver (was it the version that gets auto-installed?).

Also, there is a log file, but it probably isn't going to be much use. Any errors would have got written to stderr.

**Comment by weskerfoot** [comment]
Also another thing worth noting is that sometimes Facebook will take a long time to completely load (I don't know why this happens), and if it doesn't "finish loading", then Selenium will never fire certain events, and will just sit there. You can tell if the spinner icon continues going.

Also it will pause for a few seconds after loading the main page anyway, that's normal behaviour.

It's possible Facebook has rolled out a new site to a subset of users too, and I don't yet have it on my test account.

**Comment by enemymind** [comment]
version of chrome :: Version 79.0.3945.130  

Chromedriver was auto installed yes.

**Comment by weskerfoot** [comment]
Hmm, I have the exact same version installed. I suspect it has something to do with Facebook rolling out changes.

I'll try to push some changes to log things better. I suspect it has something to do with this line here

https://github.com/weskerfoot/DeleteFB/blob/98c20b2f9a0cd9cf97b46d89cadd41641841a898/deletefb/tools/wall.py#L27

Does it actually go to your profile page, or does it block on the main page?

**Comment by williamhammond** [comment]
I'm having a similar issue. It'll login and then go to `https://www.facebook.com/PROFILE_NAME/timeline`. It'll also pass in the year parameter if you specify but it doesn't seem to change anything. 

Full Command : `python -m deletefb.deletefb -E $EMAIL -P $PASS -U $URL -M wall -Y 2019`
OS: Ubuntu 18.04.4 LTS
Chrome version info: 
```

Google Chrome | 79.0.3945.130 (Official Build) (64-bit)
-- | --
Revision | e22de67c28798d98833a7137c0e22876237fc40a-refs/branch-heads/3945@{#1047}
OS | Linux
JavaScript | V8 7.9.317.33
Flash | 32.0.0.321 /home/wham/.config/google-chrome/PepperFlash/32.0.0.321/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service
```

**Comment by weskerfoot** [comment]
@williamhammond I suspect some exceptions are getting thrown but swallowed. I just pushed a change to master that will log them to the console. Can you install from master and try again and let me know if you see anything? It sounds like something changed and it broke the `wall` module.

**Comment by williamhammond** [comment]
Got 
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wham/Code/DeleteFB/deletefb/deletefb.py", line 137, in <module>
    run_delete()
  File "/home/wham/Code/DeleteFB/deletefb/deletefb.py", line 123, in run_delete
    year=args.year
  File "/home/wham/Code/DeleteFB/deletefb/tools/wall.py", line 27, in delete_posts
    driver.get(user_profile_url)
  File "/home/wham/Code/DeleteFB/deletefb/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/wham/Code/DeleteFB/deletefb/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/wham/Code/DeleteFB/deletefb/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=79.0.3945.130)
```

**Comment by weskerfoot** [comment]
Thank you, that's very helpful. It looks like it could potentially be an
issue with the URL that is getting passed to Selenium. I think it might
make sense to add some validation to that (or try to ensure it's always
valid). It might not like leading/trailing whitespace, or it could be
another issue, but it definitely looks like it's having trouble getting the
URL.

**Comment by williamhammond** [comment]
Ah! So that issue is that I was doing `facebook.com` rather than `https://facebook.com`. I was a little tired last night so I didn't notice that it wasn't failing the same way I'd seen before. After i readded `https` it made it to the my homepage (that previous error message actually just died on the home page) and I saw this in the logs...

```
Message: no such element: Unable to locate element: {"method":"css selector","selector":"._4xev"}
  (Session info: chrome=79.0.3945.130)

Message: no such element: Unable to locate element: {"method":"css selector","selector":"._4xev"}
  (Session info: chrome=79.0.3945.130)

Message: no such element: Unable to locate element: {"method":"css selector","selector":"._4xev"}
  (Session info: chrome=79.0.3945.130)
```
It hangs and repeats this message

**Comment by weskerfoot** [comment]
@williamhammond So that seems to confirm what I thought might be an issue. The CSS selectors are no longer working. Any chance you could open up the inspector in chrome and share the html content of the wall? Obviously you can remove anything sensitive. It has to be through the inspector and not view-source since everything is dynamically created.

Alternatively, I might just try and tackle https://github.com/weskerfoot/DeleteFB/issues/74 or https://github.com/weskerfoot/DeleteFB/issues/39 which would probably solve the problem by using the activity log to delete stuff instead of the wall.
