### ISSUE TITLE
Can we have a more robust solution? [Suggestions for improvement]

### ISSUE THREAD

**Issue by gnanakeethan** [weskerfoot/DeleteFB#11]
https://chrome.google.com/webstore/detail/social-book-post-manager/ljfidlkcmdmmibngdfikhffffdmphjae

I use this for a long time. Is there any plan to have some functionality like this?

**Comment by weskerfoot** [comment]
Planning on adding:
- Filter by year
- Schedule using a cron-like system
- Run in the background as a daemon

See https://github.com/weskerfoot/DeleteFB/issues/3 and https://github.com/weskerfoot/DeleteFB/issues/2

**Comment by russkel** [comment]
Just wanted to throw this out there and this seems like the issue to do it in. Have you looked at using the mbasic.facebook.com interface instead of the JS heavy normal interface?

**Comment by weskerfoot** [comment]
> mbasic.facebook.com

I hadn't considered that, but it makes a lot of sense! I'm not sure yet what's possible with that interface vs. the desktop one but it will definitely come in handy. Thanks for the idea.

**Comment by weskerfoot** [comment]
> Just wanted to throw this out there and this seems like the issue to do it in. Have you looked at using the mbasic.facebook.com interface instead of the JS heavy normal interface?

I hadn't considered that, but it makes a lot of sense! I'm not sure yet what's possible with that interface vs. the desktop one but it will definitely come in handy. Thanks for the idea.

**Comment by weskerfoot** [comment]
For at least pages, the mobile interface seems to not have any way to show a full list of everything you've liked

https://mobile.facebook.com/pages/?ref_type=bookmark&ref_component=mbasic_bookmark&ref_page=XMenuController

All I see here are pages I own and "suggested" pages.

Does anyone know if there is a way to see all pages you've liked, and unlike them, in the mobile interface?

**Comment by jackmahoney** [comment]
Moved out of the browser and replicating the calls made by the mobile website seems like a better way to go. Selenium is really slow. One could parallelize the http calls by using non-official api requests instead

**Comment by weskerfoot** [comment]
The tool uses the mobile interface extensively for comments now. I think it would be pretty easy to try and do it for wall posts too but I don't see any need right now.

There have been a lot of suggestions to use the functionality Facebook has built for managing your activity across the whole site. I think that is the way forward for this tool.
