### ISSUE TITLE
update chromedriver to 80

### ISSUE THREAD

**Issue by sharath-psh** [weskerfoot/DeleteFB#110]
current script automatically downloads chromedriver 78 but the current latest stable version of chrome which everyone uses is chrome 80 , please update the chromedriver to support chrome 80.

**Comment by weskerfoot** [comment]
It's in progress :) I had some issues testing on windows but it should be sorted out soon https://github.com/weskerfoot/DeleteFB/pull/105

**Comment by weskerfoot** [comment]
I can update the version that's hardcoded for now I suppose

**Comment by weskerfoot** [comment]
Updated the major version to 80. That should solve it for now. I hope to get the branch that auto-detects the version merged at some point in order to solve this issue.

**Comment by weskerfoot** [comment]
This will now dynamically generate the correct chromedriver version based on your google chrome / chromium version so it should not be an issue again
