### ISSUE TITLE
Delete Hidden Conversations

### ISSUE THREAD

**Issue by maxexcloo** [weskerfoot/DeleteFB#117]
Is it possible to add support for deleting hidden convos?

**Comment by weskerfoot** [comment]
Hmm, I had never considered that. If I get time I can take a look at the code and try to get it working.

The code depends on the mobile version of the site though, and it appears if I go to `https://mobile.facebook.com/messages/?folder=action%3Aarchived&refid=11` it shows no results, even though I can see "hidden" (archived) chats in the desktop version of the site.

**Comment by weskerfoot** [comment]
Looks like for some reason they don't support this feature on the mobile version of the site. I'm not sure what a good workaround would be other than unarchiving everything.

**Comment by maxexcloo** [comment]
I managed to do it using Selenium IDE on the desktop version. My template is attached in case it helps anyone else :)


[Delete Messages.side.zip](https://github.com/weskerfoot/DeleteFB/files/4272831/Delete.Messages.side.zip)
