### ISSUE TITLE
Prefer chromedriver in $PATH

### ISSUE THREAD

**Issue by JeffCarpenter** [weskerfoot/DeleteFB#119]
Hi there,

I have chromedriver and Chromium 80 installed on my machine, but when I ran deletefb, it downloaded an older copy of chromedriver and exited with an error that it only supports Chrome 78. 
 
Thanks for the handy script, and if you'd like a PR I'd be happy to send one your way.

**Comment by weskerfoot** [comment]
Hey, this should be fixed (regarding the out of date chromedriver) in the latest commit, but I haven't done a release yet. I'll try to do one today.

For preferring the version in the `$PATH`, yes please go ahead and submit a PR!

**Comment by weskerfoot** [comment]
I just merged some changes that should improve this logic even more and keep versioned chromedriver binaries in your user cache directory. Please let me know if version `1.1.13` (just released to PyPI) solves your problem, thanks!

**Comment by JeffCarpenter** [comment]
Yep, it goes right ahead and downloads chromedriver 80. Thanks
