### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by hemlok89** [weskerfoot/DeleteFB#123]
I am stuck on instaling via pip. Here is a [screenshot](https://i.imgur.com/pkdkx55.png)

**Comment by weskerfoot** [comment]
Hey, it looks like the `pybloom-live` library is compiling some code during the build. I think you're going to need to install MSVC in order to get it to work. 

Try downloading it from [here](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) and see if that solves the issue.

**Comment by hemlok89** [comment]
It still showing failed to build bitarray.

**Here is the output:**

Collecting delete-facebook-posts
  Using cached delete_facebook_posts-1.1.13-py3-none-any.whl (19 kB)
Requirement already satisfied: lxml in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (4.5.0)
Requirement already satisfied: requests in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (2.23.0)
Collecting pendulum
  Using cached pendulum-2.1.0.tar.gz (80 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing c:\users\saikat\appdata\local\pip\cache\wheels\0e\c7\34\96abd317fb6b76d25f6ca81878ce1a097fab6e68ed567966b4\pybloom_live-3.0.0-py3-none-any.whl
Collecting cattrs-3.8
  Using cached cattrs_3.8-0.9.1-py2.py3-none-any.whl (14 kB)
Processing c:\users\saikat\appdata\local\pip\cache\wheels\2c\67\ed\d84123843c937d7e7f5ba88a270d11036473144143355e2747\progressbar-2.5-py3-none-any.whl
Requirement already satisfied: clint in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (0.5.1)
Requirement already satisfied: appdirs in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (1.4.3)
Requirement already satisfied: attrs in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (19.3.0)
Requirement already satisfied: selenium in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (3.141.0)
Requirement already satisfied: selenium-requests in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (2.9)
Collecting python-dateutil<3.0,>=2.6
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytzdata>=2018.3
  Using cached pytzdata-2019.3-py2.py3-none-any.whl (489 kB)
Collecting bitarray>=0.3.4
  Using cached bitarray-1.2.1.tar.gz (48 kB)
Requirement already satisfied: args in c:\users\saikat\appdata\roaming\python\python38\site-packages (from clint->delete-facebook-posts) (0.1.0)
Requirement already satisfied: six in c:\users\saikat\appdata\roaming\python\python38\site-packages (from selenium-requests->delete-facebook-posts) (1.14.0)
Requirement already satisfied: tldextract in c:\users\saikat\appdata\roaming\python\python38\site-packages (from selenium-requests->delete-facebook-posts) (2.2.2)
Requirement already satisfied: setuptools in c:\users\saikat\appdata\local\programs\python\python38-32\lib\site-packages (from tldextract->selenium-requests->delete-facebook-posts) (41.2.0)
Requirement already satisfied: requests-file>=1.4 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from tldextract->selenium-requests->delete-facebook-posts) (1.4.3)
Building wheels for collected packages: pendulum, bitarray
  Building wheel for pendulum (PEP 517) ... done
  Created wheel for pendulum: filename=pendulum-2.1.0-cp38-cp38m-win32.whl size=207492 sha256=bae89b4c7c332bddae1f5e7e863d666454f50007a9d3443fbd078a19bc3d93d2
  Stored in directory: c:\users\saikat\appdata\local\pip\cache\wheels\07\6b\99\4799713ce545b81a69a18e944262ababe0277081714bea0440
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\saikat\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Saikat\AppData\Local\Temp\pip-wheel-oaky5ujy'
       cwd: C:\Users\Saikat\AppData\Local\Temp\pip-install-dl_0u_1b\bitarray\
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  creating build\lib.win32-3.8\bitarray
  copying bitarray\test_bitarray.py -> build\lib.win32-3.8\bitarray
  copying bitarray\test_util.py -> build\lib.win32-3.8\bitarray
  copying bitarray\util.py -> build\lib.win32-3.8\bitarray
  copying bitarray\__init__.py -> build\lib.win32-3.8\bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
Successfully built pendulum
Failed to build bitarray
Installing collected packages: python-dateutil, pytzdata, pendulum, bitarray, pybloom-live, cattrs-3.8, progressbar, delete-facebook-posts
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikat\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Saikat\AppData\Local\Temp\pip-record-7_rnoc4q\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Saikat\AppData\Roaming\Python\Python38\Include\bitarray'
         cwd: C:\Users\Saikat\AppData\Local\Temp\pip-install-dl_0u_1b\bitarray\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\bitarray
    copying bitarray\test_bitarray.py -> build\lib.win32-3.8\bitarray
    copying bitarray\test_util.py -> build\lib.win32-3.8\bitarray
    copying bitarray\util.py -> build\lib.win32-3.8\bitarray
    copying bitarray\__init__.py -> build\lib.win32-3.8\bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\saikat\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Saikat\AppData\Local\Temp\pip-record-7_rnoc4q\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Saikat\AppData\Roaming\Python\Python38\Include\bitarray' Check the logs for full command output.

**Comment by hemlok89** [comment]
Same problem. Showing failed to build bitarray. I installed the C++ build tool.

Here is the output:

Collecting delete-facebook-posts
  Using cached delete_facebook_posts-1.1.13-py3-none-any.whl (19 kB)
Requirement already satisfied: lxml in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (4.5.0)
Requirement already satisfied: requests in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (2.23.0)
Collecting pendulum
  Using cached pendulum-2.1.0.tar.gz (80 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing c:\users\saikat\appdata\local\pip\cache\wheels\0e\c7\34\96abd317fb6b76d25f6ca81878ce1a097fab6e68ed567966b4\pybloom_live-3.0.0-py3-none-any.whl
Collecting cattrs-3.8
  Using cached cattrs_3.8-0.9.1-py2.py3-none-any.whl (14 kB)
Processing c:\users\saikat\appdata\local\pip\cache\wheels\2c\67\ed\d84123843c937d7e7f5ba88a270d11036473144143355e2747\progressbar-2.5-py3-none-any.whl
Requirement already satisfied: clint in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (0.5.1)
Requirement already satisfied: appdirs in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (1.4.3)
Requirement already satisfied: attrs in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (19.3.0)
Requirement already satisfied: selenium in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (3.141.0)
Requirement already satisfied: selenium-requests in c:\users\saikat\appdata\roaming\python\python38\site-packages (from delete-facebook-posts) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from requests->delete-facebook-posts) (2.9)
Collecting python-dateutil<3.0,>=2.6
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytzdata>=2018.3
  Using cached pytzdata-2019.3-py2.py3-none-any.whl (489 kB)
Collecting bitarray>=0.3.4
  Using cached bitarray-1.2.1.tar.gz (48 kB)
Requirement already satisfied: args in c:\users\saikat\appdata\roaming\python\python38\site-packages (from clint->delete-facebook-posts) (0.1.0)
Requirement already satisfied: six in c:\users\saikat\appdata\roaming\python\python38\site-packages (from selenium-requests->delete-facebook-posts) (1.14.0)
Requirement already satisfied: tldextract in c:\users\saikat\appdata\roaming\python\python38\site-packages (from selenium-requests->delete-facebook-posts) (2.2.2)
Requirement already satisfied: setuptools in c:\users\saikat\appdata\local\programs\python\python38-32\lib\site-packages (from tldextract->selenium-requests->delete-facebook-posts) (41.2.0)
Requirement already satisfied: requests-file>=1.4 in c:\users\saikat\appdata\roaming\python\python38\site-packages (from tldextract->selenium-requests->delete-facebook-posts) (1.4.3)
Building wheels for collected packages: pendulum, bitarray
  Building wheel for pendulum (PEP 517) ... done
  Created wheel for pendulum: filename=pendulum-2.1.0-cp38-cp38m-win32.whl size=207492 sha256=bae89b4c7c332bddae1f5e7e863d666454f50007a9d3443fbd078a19bc3d93d2
  Stored in directory: c:\users\saikat\appdata\local\pip\cache\wheels\07\6b\99\4799713ce545b81a69a18e944262ababe0277081714bea0440
  Building wheel for bitarray (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\saikat\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Saikat\AppData\Local\Temp\pip-wheel-oaky5ujy'
       cwd: C:\Users\Saikat\AppData\Local\Temp\pip-install-dl_0u_1b\bitarray\
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  creating build\lib.win32-3.8\bitarray
  copying bitarray\test_bitarray.py -> build\lib.win32-3.8\bitarray
  copying bitarray\test_util.py -> build\lib.win32-3.8\bitarray
  copying bitarray\util.py -> build\lib.win32-3.8\bitarray
  copying bitarray\__init__.py -> build\lib.win32-3.8\bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for bitarray
  Running setup.py clean for bitarray
Successfully built pendulum
Failed to build bitarray
Installing collected packages: python-dateutil, pytzdata, pendulum, bitarray, pybloom-live, cattrs-3.8, progressbar, delete-facebook-posts
    Running setup.py install for bitarray ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\saikat\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Saikat\AppData\Local\Temp\pip-record-7_rnoc4q\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Saikat\AppData\Roaming\Python\Python38\Include\bitarray'
         cwd: C:\Users\Saikat\AppData\Local\Temp\pip-install-dl_0u_1b\bitarray\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\bitarray
    copying bitarray\test_bitarray.py -> build\lib.win32-3.8\bitarray
    copying bitarray\test_util.py -> build\lib.win32-3.8\bitarray
    copying bitarray\util.py -> build\lib.win32-3.8\bitarray
    copying bitarray\__init__.py -> build\lib.win32-3.8\bitarray
    running build_ext
    building 'bitarray._bitarray' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\saikat\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"'; __file__='"'"'C:\\Users\\Saikat\\AppData\\Local\\Temp\\pip-install-dl_0u_1b\\bitarray\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Saikat\AppData\Local\Temp\pip-record-7_rnoc4q\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Saikat\AppData\Roaming\Python\Python38\Include\bitarray' Check the logs for full command output.

**Comment by weskerfoot** [comment]
You may have better luck with the docker version of the tool. I recommend giving that a shot. Also, you could try using the WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10). I don't have a windows machine/VM handy to test it out right now, but if I get a chance I'll give it a shot and document how to use it.
