### ISSUE TITLE
Unable to locate element: {"method":"css selector","selector":"._4xev"}

### ISSUE THREAD

**Issue by tabekooi** [weskerfoot/DeleteFB#128]
Message: no such element: Unable to locate element: {"method":"css selector","selector":"._4xev"}
  (Session info: chrome=81.0.4044.113)

this happens after chrome goes to the profile url.

**Comment by weskerfoot** [comment]
I can see it does log that message but interestingly it still seems to manage to delete posts. I think it's because something changed, but I'm not sure why it still works for me. I'll see if I can fix the broken selector though.

**Comment by weskerfoot** [comment]
Looks like the CSS selector is still the same. It just isn't showing up right away, but it eventually finds it. Does deleting work for you still?

**Comment by weskerfoot** [comment]
Do you by any chance have the "new" Facebook frontend enabled? That would completely break everything.

**Comment by tabekooi** [comment]
Yep, thats it than.

**Comment by weskerfoot** [comment]
Leaving this open till there's a fix for forcing the mobile site to be used (which should fix it)

**Comment by zhanming-wang** [comment]
Same problem here. Is there a way to get around this?

**Comment by michellekusold** [comment]
I love this tool. Thanks for making it. Unfortunately, the new facebook is here to stay. I filed a support ticket asking for the old version so I could use this tool, but I haven't been able to get a response. Do you know of anyway of forcing the old UI back? otherwise, we may be forced to update. I'd be happy to contribute to the code if that's the case.

**Comment by weskerfoot** [comment]
> I love this tool. Thanks for making it. Unfortunately, the new facebook is here to stay. I filed a support ticket asking for the old version so I could use this tool, but I haven't been able to get a response. Do you know of anyway of forcing the old UI back? otherwise, we may be forced to update. I'd be happy to contribute to the code if that's the case.

I do not know if there is a way of forcing it. PRs for this would be welcome if you want to do the work of figuring out how to fix it though. At the moment I'm not too focused on this but I would be happy to review and approve it.

**Comment by weskerfoot** [comment]
Hoping to put some time towards refactoring this soon

**Comment by IsaacBamwidhi** [comment]
> 
> 
> I love this tool. Thanks for making it. Unfortunately, the new facebook is here to stay. I filed a support ticket asking for the old version so I could use this tool, but I haven't been able to get a response. Do you know of anyway of forcing the old UI back? otherwise, we may be forced to update. I'd be happy to contribute to the code if that's the case.

It is possible to to switch to the classic view. That is what I have done. However, after this month, we shall all be forced to use the new version. 

It will be nice to get a way around this though.

**Comment by weskerfoot** [comment]
looks like I have the new facebook, I'll start trying to hack together support for it soon

**Comment by weskerfoot** [comment]
working on getting this to work today, it's a bit challenging to extract the content and timestamp of posts now

**Comment by weskerfoot** [comment]
will likely force the mobile site to work around issues

**Comment by weskerfoot** [comment]
https://github.com/weskerfoot/DeleteFB/pull/129

**Comment by weskerfoot** [comment]
should be fixed now, new release coming soon

**Comment by RichardBean** [comment]
I downloaded DeleteFB today, and got this message, because I installed with "pip3 install --user delete-facebook-posts" on Windows 10. That gave me version 1.1.14 from April 1. I needed to get the ChromeDriver exe file from the zip at https://sites.google.com/a/chromium.org/chromedriver/home then I went to the DeleteFB home page, under the green "Code", download zip, then "pip3 install --user .", then it said it was deleting 1.1.14 and installing 1.1.13, and now it is working. Hooray!

**Comment by weskerfoot** [comment]
> I downloaded DeleteFB today, and got this message, because I installed with "pip3 install --user delete-facebook-posts" on Windows 10. That gave me version 1.1.14 from April 1. I needed to get the ChromeDriver exe file from the zip at https://sites.google.com/a/chromium.org/chromedriver/home then I went to the DeleteFB home page, under the green "Code", download zip, then "pip3 install --user .", then it said it was deleting 1.1.14 and installing 1.1.13, and now it is working. Hooray!

Hi, sorry about that. I just pushed a new release now. I was too busy to do it earlier and had forgotten, thanks for using it!
