### ISSUE TITLE
Scramble the posts before deleting them

### ISSUE THREAD

**Issue by Nodraak** [weskerfoot/DeleteFB#13]
[From HackerNews](https://news.ycombinator.com/item?id=19964087): "I think the more effective script would be one that goes through all of your FB posts and scrambles them, or replaces the text with gibberish."

For more confidence, it could be nice to update the post with random data and then delete it.

**Comment by weskerfoot** [comment]
I thought about this and I think I would want it to be off by default, but I think it could potentially be useful.

The trick would be to do it in such a way that it won't cause Facebook to flag your account as being hacked.

**Comment by AlexMason** [comment]
Edited posts have a "history" on FB... so this would be useless in effect.

**Comment by Nodraak** [comment]
Yes, you are totally right, I did not thought about that. Guess I can close the PR then XD
