### ISSUE TITLE
bash: password: event not found

### ISSUE THREAD

**Issue by gqueruel** [weskerfoot/DeleteFB#14]
Hi,
I tried to execute deletefb according to the readme file but I encountered an "even not found" issue with some portion of my password.

**Comment by ConnorSkees** [comment]
Could you post the full stack trace here and format it as a code block by surrounding it in backticks, \`\`\`stacktrace\`\`\`

**Comment by Nodraak** [comment]
Your password probably contains a quote and a `!`, which causes bash to interpret it. Make sure that you enter your password between quotes and escape any quotes that are inside your password. For instance, if your password is `he"llo!world`, use `deletefb [...] -P "he\"llo!world" [...]`.
Hope this helps

**Comment by weskerfoot** [comment]
Once https://github.com/weskerfoot/DeleteFB/issues/15 is implemented then it would allow you to copy and paste it in without escaping

**Comment by millgatephil** [comment]
Your password contains a !

Wrap your password in single quotes ' instead of double quotes, and it will work correctly.
