### ISSUE TITLE
Page not found error when script navigates to "/timeline" page

### ISSUE THREAD

**Issue by waddington** [weskerfoot/DeleteFB#141]
Hi,

I have just come across this script so maybe I am doing something wrong.

Once the script has logged in it attempts to navigate to something like mobile.facebook.com/my.username/timeline, when it does this facebook shows a page not found error page, and thus the script exits.

I run the script in an anaconda environment using `python -m deletefb.deletefb -E "email address" -P "password" -U "profile url without trailing slash" -Y 2009`

Any idea's?

Thanks

Edit: I see that this is duplicate of #131

**Comment by weskerfoot** [comment]
Can you try with this branch? https://github.com/weskerfoot/DeleteFB/tree/fix-year

I'm unable to test at the moment since I don't have any posts

**Comment by weskerfoot** [comment]
actually nevermind, working on a different approach to this

**Comment by weskerfoot** [comment]
closing since this is a duplicate and the fix will be tracked in https://github.com/weskerfoot/DeleteFB/issues/131
