### ISSUE TITLE
Windows bug

### ISSUE THREAD

**Issue by privacyguy123** [weskerfoot/DeleteFB#148]
Seeing 
```
ImportError: cannot import name '_Union' from 'typing' (C:\Python39\lib\typing.py)
```

when I try to run

**Comment by weskerfoot** [comment]
I think this is the same issue as https://github.com/weskerfoot/DeleteFB/issues/96
 
See if the suggestions there help?

**Comment by weskerfoot** [comment]
@privacyguy123 what's the full traceback look like? is it coming from cattrs?

**Comment by weskerfoot** [comment]
this should be fixed with the changes I just made, will have to release a new version though...
