### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by wrapper** [weskerfoot/DeleteFB#152]
Hey there

Thanks for continuing to maintain this. I just tried to run in a virtualenv on linux, 
The browser window opens, the login dialogue populates and then the browser closes. I get the following error:

```
An exception occurred: Message: element click intercepted: Element <button value="1" class="_42ft _4jy0 _52e0 _4jy6 _4jy1 selected _51sy" id="loginbutton" name="login" tabindex="0" type="submit">...</button> is not clickable at point (1712, 341). Other element would receive the click: <div class="_9fwj">...</div>
  (Session info: chrome=83.0.4103.116)

'NoneType' object has no attribute 'get'
```

Thanks

**Comment by MichaelHarkins** [comment]
not a contributor, but can you add what version of python, etc you are using?
 I am using a newer chrome driver (87.0), and I am able to login. I am also using python 3.9. 
I installed by using github to clone into a virtualenv and the did a pip3 install -r. I ran using deletefb -E 'email' -P 'password' -U 'profileurl'

I am running on mac osx,hope this helps

**Comment by wrapper** [comment]
Thanks for your reply. I'm using python 3.8. After some messing around I got my chromium up to 87, only to get the same error in the end:

```
An exception occurred: Message: element click intercepted: Element <button value="1" class="_42ft _4jy0 _52e0 _4jy6 _4jy1 selected _51sy" id="loginbutton" name="login" tabindex="0" type="submit">...</button> is not clickable at point (1712, 341). Other element would receive the click: <div class="_9fwj">...</div>
  (Session info: chrome=87.0.4280.88)

```

**Comment by wrapper** [comment]
Okay, the issue was actually this - https://github.com/weskerfoot/DeleteFB/issues/142

Needs to be added to the documentation
