### ISSUE TITLE
Crashes once logged in

### ISSUE THREAD

**Issue by SeanDS** [weskerfoot/DeleteFB#160]
Running the latest pip version of DeleteFB (1.1.17) with the latest Chrome (89.0.4389.114) I get the following issues: first if I run `deletefb -E myemail -U myuser -P mypassword`, Chrome opens and I get the login page and cookie permission popup. Doing nothing, I get

```
An exception occurred: Message: element click intercepted: Element <button value="1" class="_42ft _4jy0 _52e0 _4jy6 _4jy1 selected _51sy" id="loginbutton" name="login" tabindex="0" type="submit">...</button> is not clickable at point (952, 341). Other element would receive the click: <div>...</div>
    (Session info: chrome=89.0.4389.114)

'NoneType' object has no attribute 'get'
```

If I re-run but this time manually click the cookie accept button quickly, it logs in, shows my home page but then crashes after a few seconds with the error

```
Message: invalid argument
    (Session info: chrome=89.0.4389.114)
```

Any ideas what's happening here?

**Comment by SeanDS** [comment]
Ok, some poking around I managed to figure out the problem: the `force_mobile` function returns a URL that starts `//mobile.facebook.com` but [this StackOverflow answer](https://stackoverflow.com/a/57483869/2251982) suggests you need a protocol. I hacked `force_mobile` to add `https` to the start of the URL and it then worked.

**Comment by weskerfoot** [comment]
> Ok, some poking around I managed to figure out the problem: the `force_mobile` function returns a URL that starts `//mobile.facebook.com` but [this StackOverflow answer](https://stackoverflow.com/a/57483869/2251982) suggests you need a protocol. I hacked `force_mobile` to add `https` to the start of the URL and it then worked.

If you make a PR for it I can merge it
