### ISSUE TITLE
Use the getpass module instead of "input" for obtaining user passwords 

### ISSUE THREAD

**Issue by ijustlovemath** [weskerfoot/DeleteFB#18]
https://github.com/weskerfoot/DeleteFB/blob/748bd851e72881d55022bf14381ec52116a8c9e0/deletefb/deletefb.py#L54

**Comment by ijustlovemath** [comment]
@weskerfoot would you accept a pull request if I made one? I think this lies more in the security realm than the enhancement realm

**Comment by ijustlovemath** [comment]
Just created a pull request, it's a pretty simple drop-in replacement: https://github.com/weskerfoot/DeleteFB/pull/19

**Comment by weskerfoot** [comment]
Fixed in https://github.com/weskerfoot/DeleteFB/pull/19

Thanks!
