### ISSUE TITLE
Support unlike all pages

### ISSUE THREAD

**Issue by wicey** [weskerfoot/DeleteFB#21]
I'm using facebook since I was a teenager and I liked 1000+ pages that are absolutely useless. Is there any way to unlike all the pages at once, same way you did with posts ?

**Comment by weskerfoot** [comment]
This wouldn't be too difficult to add. I'll look into it, thanks for the feedback!

**Comment by 1m2r3a** [comment]
@weskerfoot I did some digging and this might work:

- Navigate to  https://www.facebook.com/pages/?category=liked

-  After getting the id="page_browser_liked", navigate 3 div and get the page url from <a href element

`<a tabindex="-1" target="_self" href="https://www.facebook.com/PAGE_NAME_HERE/" id="u_0_13"><img class="_s0 _4ooo _1x2_ _1ve7 img" src="" alt="" aria-label="" role="img" style="width:222px;height:222px"></a>`

- Open the page, I think you can search after data-testid="page_unlike_item_test_id" to unlike the page

`<li class="_54ni __MenuItem" role="presentation"><a class="_54nc" href="#" data-testid="page_unlike_item_test_id" role="menuitem"><span><span class="_54nh">Unlike this Page</span></span></a></li>`

- Repeat until step 2 throws an exception

**Comment by weskerfoot** [comment]
Started work in https://github.com/weskerfoot/DeleteFB/pull/23

**Comment by wicey** [comment]
Thanks for the quick answer guys! Looking forward to use your tool @weskerfoot

**Comment by weskerfoot** [comment]
Working in https://github.com/weskerfoot/DeleteFB/pull/31

Needs testing by various people to make sure it works in all cases but it works well on my profile.

**Comment by TallonRain** [comment]
The `unlike_pages` option terminates prematurely after the first page of unlikes is processed. The page refreshes for the second batch and the window terminates at that point.

**Comment by weskerfoot** [comment]
Thanks for reporting. I'll see if I can find the issue.
