### ISSUE TITLE
Use Facebook API instead

### ISSUE THREAD

**Issue by ConnorSkees** [weskerfoot/DeleteFB#29]
I am just wondering if using something like requests with the [Facebook API](https://developers.facebook.com/docs/graph-api/reference/v3.3/post#deleting) would be more reliable and faster. I haven't looked into how it would work for normal users though.

**Comment by weskerfoot** [comment]
I looked into it a little bit and it seems like it might only support pages?

**Comment by weskerfoot** [comment]
I would love to find a way to do this with the API though

**Comment by hvtuananh** [comment]
I tried to use Facebook API a little while ago, but it's impossible to delete *everything*, as you can delete what you originally post using your API key.

> An app can delete any post it published, or a page-management app can delete a Post published to a Page that the app manages.

**Comment by ConnorSkees** [comment]
Ah, thank you for clarifying the documentation. That's unfortunate :(

Closing this issue as it is not feasible
