### ISSUE TITLE
Improve reliability and run daemonized

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#3]
Right now, it will just crash if it runs into any errors. It would be a nice feature if it were:

1) Able to work in headless mode, and run as a daemon.
2) Recover from crashes, and detect when you have no posts left to delete
3) Schedule deletion of posts, so that you can use it in a cron-like manner to regularly delete things you've posted.

**Comment by Nodraak** [comment]
Note: 1. is covered by #10

**Comment by weskerfoot** [comment]
One potential issue with running it as a daemon is 2FA. It will somehow require entering it the first time it is run, or they would have to disable 2FA temporarily.

**Comment by volere** [comment]
I came across a post that cannot be deleted.  It gets stuck trying to delete.  I am wondering how to tell this thing to skip elements that it can't delete.

**Comment by weskerfoot** [comment]
@volere it's been a while, but any chance you could take a screenshot? I'm curious if it had a "delete" option but simply refused to delete it. I've noticed sometimes Facebook will fail to delete certain things, but it seems like it got deleted at first (but they show up again later).

It would be awesome if you could open another issue if the problem persists.

**Comment by weskerfoot** [comment]
I think I'm going to make this be a documentation thing and simply document how this would work. I think as it is, the tool should support everything in this issue.

**Comment by weskerfoot** [comment]
I think all three of these are covered by the docker container that it can run in now, since you can easily schedule containers to run at set intervals or in the background.
