### ISSUE TITLE
Run in docker

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#34]
Would be useful to write a Dockerfile that will build an image to run it in headless mode.

This would probably require implementing proper logging so that the user can see what's going on. It would make daemonizing it trivial.

**Comment by mmatoscom** [comment]
I am doing the Dockerfile this week, won't be lightweight since we need to export X11 in order to open graphics in host (for browser/selenium), and will work only in Linux and OSX. When it work I will open a PR. cheers, Marco

**Comment by weskerfoot** [comment]
Thanks!

**Comment by mmatoscom** [comment]
I am currently stuck with the following:
/usr/bin/python3: Relative module names not supported

**Comment by weskerfoot** [comment]
Sounds like maybe an issue with setup.py ?

**Comment by weskerfoot** [comment]
@mmatoscom 
I think this line
https://github.com/mmatoscom/DeleteFB/blob/1cccf4a2c5eb2371fcba88966c81235d726715b0/Dockerfile#L77

Should be `CMD python3 -m deletefb.deletefb ` since you're executing it as a module, not directly as a script

**Comment by weskerfoot** [comment]
Also, do you think it would be possible to use alpine as the base image? Or at least a minimal debian base image?

**Comment by mmatoscom** [comment]
@weskerfoot  Hi, thanks for the messages. I will try the correct CMD, and yes i think it could be a lightweight image since we are mounting X in the host, will check today.

**Comment by mmatoscom** [comment]
@weskerfoot hi, so it worked, now I got to setup ENV vars
in order to pass them from command line when container is starting
and then check for X
```
Step 13/13 : CMD python3 -m deletefb.deletefb
 ---> Running in d65aeaf6337c
Removing intermediate container d65aeaf6337c
 ---> cd95bd7252f3
Successfully built cd95bd7252f3
Successfully tagged deletefb:latest
usage: deletefb.py [-h] [-M {wall,unlike_pages}] -E EMAIL [-P PASSWORD] -U
                   PROFILE_URL [-F TWO_FACTOR_TOKEN] [-H] [--no-archive]
                   [-Y YEAR]
deletefb.py: error: the following arguments are required: -E/--email, -U/--profile-url

```

**Comment by mmatoscom** [comment]
even using `debian:stable-slim` which is **55.3M**, the image size is **1.12GB**
but it built fine and we got the same output, will work on the env vars now

> → docker images|grep deletefb
> deletefb                         latest              b76434a64455        13 minutes ago      1.12GB
> 
> Step 12/12 : CMD python3 -m deletefb.deletefb
>  ---> Running in 654af68f5d80
> Removing intermediate container 654af68f5d80
>  ---> b76434a64455
> Successfully built b76434a64455
> Successfully tagged deletefb:latest
> usage: deletefb.py [-h] [-M {wall,unlike_pages}] -E EMAIL [-P PASSWORD] -U
>                    PROFILE_URL [-F TWO_FACTOR_TOKEN] [-H] [--no-archive]
>                    [-Y YEAR]
> deletefb.py: error: the following arguments are required: -E/--email, -U/--profile-url

**Comment by mmatoscom** [comment]
@weskerfoot  it worked!
i will open a PR, we can improve from now on
but chrome is opening, and deleting the posts !!

**Comment by weskerfoot** [comment]
@mmatoscom That's awesome, I'll test it out when I get a chance

**Comment by mmatoscom** [comment]
Hi @weskerfoot 
I am creating a Makefile to make it easier to use docker, so by typing `make` it will build the image and ask for the values as follows:
```
	@read -p "Enter your Facebook email: " email; \
	@read -p "Enter your Facebook password: " password; \
	@read -p "Enter your Facebook username: " username;
```
then spin-up the container with proper env vars loaded, almost getting there, when finished will ping you again
cheers
Marco

**Comment by weskerfoot** [comment]
Sounds good. I appreciate the effort.

**Comment by mmatoscom** [comment]
maybe this should be closed?

**Comment by weskerfoot** [comment]
Yep, I think I already closed it

**Comment by mmatoscom** [comment]
Its still open, just you and who opened this issue are able to close it
