### ISSUE TITLE
Modularize the visibility filter, content filter, action, and archive options

### ISSUE THREAD

**Issue by rshetye** [weskerfoot/DeleteFB#35]
Hi,

If you could modularize along the following lines:
- visibility filter=default is "non-hidden" (to optimise processing), can be set to "all" messages
  - content filter=default is "none" , can be set to "match keyword"
    - Pattern matching can be done by appending to the facebook url activity log itself (and thereby making facebook do the heavy lifting on the server side).
    - Inverting the keyword match, Matching a pattern, Inverting the pattern match can be stretch goals
- action=default is "hide" (non-destructive default but still private and inaccessible), can be set to "delete"
  - archive=default is "save" the fsm div to JSON whose filename is set to the original timestamp , can be set to "don't save"

then users can choose a variety of actions. e.g.
- Users can now feed a list of keywords to hide for e.g. travelling to China ? hide/delete your "Tibet" and "Hong Kong" posts.
- Users can make all posts about a specific trip private and inaccessible, while leaving the rest of their facebook content accessible

**Comment by weskerfoot** [comment]
Thanks, I'll think about this and see what I can do
