### ISSUE TITLE
Can i use it in mac with chrome?

### ISSUE THREAD

**Issue by kaushik853** [weskerfoot/DeleteFB#36]
As when i start the chromedriver ,it keeps open and display "Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port xxxx"
Is this the way it should work?

**Comment by kaushik853** [comment]
I tried to run it as python deletefb/deletefb.py -E "youremail@example.org" -P "yourfacebookpassword" -U "https://www.facebook.com/your.profile.url" 

gets error as "ModuleNotFoundError: No module named 'deletefb.tools'; 'deletefb' is not a package
"

**Comment by weskerfoot** [comment]
Hi, the recommended way of installing on MacOS is

```
brew tap homebrew/cask
brew cask install chromedriver
```
Then simply to `pip install --user delete-facebook-posts` and run it. No need to directly execute the python files.

If you do wish to do that, I have just pushed an update that will allow it with the following syntax:

```
python -m deletefb.deletefb -E "youremailhere" -P "yourpasswordhere" -U "https://www.facebook.com/your.profile"
```

**Comment by weskerfoot** [comment]
I have updated the documentation with instructions on how to do this, and changed the imports to be relative so that it will be possible to run with `python -m deletefb.deletefb` now if you *really want to*.

https://github.com/weskerfoot/DeleteFB#how-to-use-it

**Comment by kaushik853** [comment]
supercool..thanks

**Comment by kaushik853** [comment]
One query..do i get a message in cli after the completion of run/task completed ?
No ?
