### ISSUE TITLE
Stuck in login page when 'Save browser' is displayed after 2FA

### ISSUE THREAD

**Issue by indiandragon** [weskerfoot/DeleteFB#38]
Hi,

when 2FA is enabled, there are different flow involved which is currently not being handled and without which the script cannot serve its intended purpose.

'Save browser'

Each time when 2FA is enabled, save the browser screen is shown. The action is currently not being handled.  

While on 'Save browser' screen, the page is reloaded to show the time-line but since the user is not logged in yet; the script is struck in the login page again.

Temporary fix : While being struck on login screen after selecting 'Save browser', we can login manually and go to timeline page for the script to do its job. Temporary fix cannot be applied during '--headless'.

Permanent fix : Need to handle this case in the script.

**Comment by weskerfoot** [comment]
Yep, I've run into this too. Can confirm that Facebook will sometimes give you several prompts.

**Comment by weskerfoot** [comment]
Fixed in https://github.com/weskerfoot/DeleteFB/pull/67
