### ISSUE TITLE
Support for Grid View in the timeline to defeat Facebook's measures

### ISSUE THREAD

**Issue by indiandragon** [weskerfoot/DeleteFB#39]
Hi,

I had 10 years of posts to be deleted, I deleted 5 years of posts with this script and after the 5th year, Facebook disabled the ListView and only Grid View was available.

Timeline has 2 modes of displaying posts, List View & Grid View. I have reasons to believe Facebook disables the List View after deleting several posts and only Grid View is available there after.

Grid View is not currently being handled in the script.

**Comment by weskerfoot** [comment]
I've found this with page likes too. Will look into it, thanks for the info.

**Comment by weskerfoot** [comment]
This is currently blocking my testing on https://github.com/weskerfoot/DeleteFB/issues/47

I think a workaround is to check if the page has the "Review Liked Pages" card in it.

It seems like Facebook will switch you to a grid view for certain things if you delete all of your content and then re-add it. I'm not sure if there is a way to force it to use list view.

**Comment by weskerfoot** [comment]
![image](https://user-images.githubusercontent.com/378351/58741557-497b9d00-83e8-11e9-871c-625a88338329.png)

**Comment by weskerfoot** [comment]
I suspect there is some kind of feature flag that varies between accounts that is causing this to be different for some people

**Comment by weskerfoot** [comment]
It will have to support both types I guess. A reasonable approach would be to look for that "Review Liked Pages" button for pages.

For the timeline we can check for an element with the `uiGrid` class applied to it.

**Comment by weskerfoot** [comment]
Unliking pages is working without needing to differentiate between grid layouts.

I used the mobile version of the site. The same method might work for posts.

**Comment by mitar** [comment]
Why not use "Manage posts" feature of Facebook? It already allows you select and delete Facebook posts, but with limit to 50.

This is where I find it:

![(1)_Mi_Tar_-_2019-06-02_16 10 46](https://user-images.githubusercontent.com/585279/58768494-012bbe80-8551-11e9-9982-ef2eda134373.png)

**Comment by weskerfoot** [comment]
@mitar that could be more efficient, but I'm not sure how easy archiving would be

**Comment by mitar** [comment]
That manage posts also shows posts themselves? So you could extract data there? No?

Or, why not automatize using Facebook archive function to get all JSONs first? So I just noticed (used it before running this tool) that they support exporting JSONs now. To support migration to another service. It seems to contain everything.

**Comment by weskerfoot** [comment]
@mitar Cool, I wasn't sure if it only showed a summary or the whole post itself. The JSON exporting feature looks nice as well. I definitely would like to explore using that.

**Comment by mitar** [comment]
It shows some kind of thumbnails. I think content is there, but not comments on the content.

But if you click on it, you get a nice dialog box showing you content in full. It could be used to extract the post fully, if thumbnail is missing something.

**Comment by weskerfoot** [comment]
Will probably try to tackle this next, as well as improve the archiving functionality

**Comment by weskerfoot** [comment]
should no longer be an issue
