### ISSUE TITLE
bash: deletefb: command not found

### ISSUE THREAD

**Issue by mikeyyyzhao** [weskerfoot/DeleteFB#41]
I ran the instructions but for some reason when I tried running the script "deletefb -E ...", it gave me a "bash: deletefb: command not found" error. Here's the code I ran:

1. pip install --user delete-facebook-posts
2. brew tap homebrew/cask;
3. brew cask install chromedriver
4. "deletefb -E "

**Comment by weskerfoot** [comment]
Check your `$PATH` variable. Your shell might not be set up to discover scripts installed by pip. E.g. on my system it gets put under `~/.local/bin/deletefb`

**Comment by Billydubb** [comment]
In case anyone else could not find it in `~/.local/bin/deletefb`, on my system it was installed in `/Users/<USERNAME>/Library/Python/2.7/bin`.

**Comment by xtremehume** [comment]
mine was installed in `/Users/<USERNAME>/Library/Python/2.7/bin` but how do you get it working? i tried copying the deletefb script fiel to `~/.local/bin/deletefb` but that returns 

> ValueError: Unable to configure handler 'file_handler'

**Comment by Billydubb** [comment]
I ended up cloning the repo and running `python3 . ` in the directory where the `__main__.py` file is located. I got some error messages regarding imports. Not sure which ones exactly anymore though. They were related to imports and quite easy to resolve however.
