### ISSUE TITLE
__init__() got an unexpected keyword argument 'options'

### ISSUE THREAD

**Issue by mikeyyyzhao** [weskerfoot/DeleteFB#46]
This might be a noob mistake but I'm getting "__init__() got an unexpected keyword argument 'options'" after trying to run the script. The error tells me to install chromedriver for Selenium but I already have it since when I run "chromedriver --version", I get a proper version back.

**Comment by weskerfoot** [comment]
Are you running it in a virtualenv?

**Comment by weskerfoot** [comment]
Please re-open if you still need help with this

**Comment by jhgarcia0** [comment]
> Please re-open if you still need help with this



> Are you running it in a virtualenv?
> 
> Also what OS, version of Python, etc
> 
> Also if you could give me the output of `pip3 show selenium`
> 
> (And make sure you installed it with Python 3 pip if you installed it with pip, that should have been in the docs somewhere but I think it got changed at some point to just be `pip` instead of `pip3`)

Hey! I'm getting the same error in a virtualenv, I'm using the site "pythoneverywhere", do you know how can I solve that?
