### ISSUE TITLE
Support headless mode

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#5]
I haven't tested this but it shouldn't make any difference. It is a prerequisite for running it as a daemon.

**Comment by NaveenPrasanth** [comment]
Is the idea to run the headless as the background process? 
I'm thinking what you might have in mind because I assume selenium needs the browser in the foreground for this to work, correct?

**Comment by Suleman-Elahi** [comment]
Nope. The browser doesn't need be in foreground because it is not the mouse or keyboard doing the work, Chrome driver is.
