### ISSUE TITLE
Pause to enter two-factor authentication code

### ISSUE THREAD

**Issue by cyphar** [weskerfoot/DeleteFB#6]
Currently the delay between login and trying to start deleting posts is far too short, resulting in it being quite difficult to get the script to wait while I complete the login process.

**Comment by weskerfoot** [comment]
I hadn't considered this. I'll look into testing that out and see what I can come up with.

**Comment by weskerfoot** [comment]
Should be fixed now. I tested it and 20 seconds should be a good amount of time to enter 2FA codes. It should only pause if it encounters the 2FA prompt as well.
