### ISSUE TITLE
Refactor archiver into class

### ISSUE THREAD

**Issue by ConnorSkees** [weskerfoot/DeleteFB#62]
Hello! I was thinking that a better way to structure the archival(?) system would be to have it in a class somewhat like this:
```python
import os
from os.path import abspath, curdir, isdir
import uuid

class Archive:
    ARCHIVE_TYPES = ["posts", "likes", "wall", "photos"]
    def __init__(self):
        self.original_dir = curdir
        if abspath(curdir).endswith(("tools",)):
            os.chdir("..")

        if not isdir("archive"):
            os.mkdir("archive")

        os.chdir("archive")

        for archive_type in self.ARCHIVE_TYPES:
            if not os.path.isdir(archive_type):
                os.mkdir(archive_type)

    def __del__(self):
        os.chdir(self.original_dir)

    def post(self, data):
        directory = "posts/{0}".format(data["date"])  # date in ISO 8601
        os.mkdir(directory)
        with open(directory + "/{0}.json".format(uuid.uuid4()), mode="w") as f:
            json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)

    def likes(self, data):
        pass

    def wall(self, data):
        pass

    def photos(self, data):
        pass
```

where the data for the post would look like
```javascript
data = {
  "date": "2019-06-03T00:00:00",
  "content": "lorem ipsum sit amet",
  "comments": [
    {
      "poster": "alexJOnes",
      "content": "foobar baz quinquoz"
    }
  ],
  "reactions": {
    "like": ["user3"],
    "love": [],
    "sad": ["user1", "user2"],
    "haha": [],
    "wow": [],
    "angry": [],
  }
}
```

I don't use Facebook so I'm not totally sure what other information is given/relevant. I used a uuid as the filename because when I looked, all posts only had dates and not times associated with them and posts don't normally have titles. It might also be worthwhile to sanitize the comments with [emoji](https://github.com/carpedm20/emoji)

Please let me know what your thoughts are :)

**Comment by weskerfoot** [comment]
It's an interesting idea. Maybe https://docs.python.org/3/library/pathlib.html could help with handling paths.

I would like to make the location of archives user-configurable as well in order to avoid having to make assumptions about where they want their archive stored (maybe default to the current working directory).

I think it would make most sense, if this is to be a class, that it should have the archive type passed in via the constructor. That way you could safely run multiple instances concurrently for different things (at least in principle).

To that end, I recommend checking out https://github.com/python-attrs/attrs which makes it a lot easier to build classes (gives you a lot of things for free, like conversion to dictionaries).

We should model it as a class with attrs attributes and then leverage the `.asdict()` functionality.

Hopefully that makes sense.

**Comment by weskerfoot** [comment]
Here's a quick sketch

```
#! /usr/bin/env python3

import attr
import datetime
import uuid

@attr.s
class Post:
    content = attr.ib()
    comments = attr.ib(default=[])
    date = attr.ib(factory=datetime.datetime.now)
    name = attr.ib(factory=uuid.uuid4)

@attr.s
class Comment:
    commenter = attr.ib()
    content = attr.ib()
    date = attr.ib(factory=datetime.datetime.now)
    name = attr.ib(factory=uuid.uuid4)

@attr.s
class Archive:
    archive_type = attr.ib()

    archive_dir = attr.ib(default="~/.deletefb_archive")

    def archive(self, content):
        # do something
        print("Archiving type {0} with content {1} to directory {2}".format(self.archive_type, content, self.archive_dir))

archive = Archive(archive_type="wall")

archive.archive(Post(content="A post!"))
archive.archive(Comment(commenter="Bob", content="Nice post!"))
```

**Comment by ConnorSkees** [comment]
Yeah, it makes sense to be able to specify a directory to put the archived info in. Do you think that should be done through the config file, as a cli flag, or both? 

This line, 
```python
archive_dir = attr.ib(default="~/.deletefb_archive")
```
on Windows I believe the equivalent would be `%USERPROFILE%`. I guess we would have to do something like
```python
IS_WINDOWS = os.name == 'nt'
default directory = "%USERPROFILE%/.deletefb_archive" if IS_WINDOWS else "~/.deletefb_archive"
```

**Comment by weskerfoot** [comment]
@ConnorSkees Yeah it would have to be somewhat portable, or at least print out a warning telling the user to manually configure it if it can't find the directory.

**Comment by weskerfoot** [comment]
I'm going to work on this today.

**Comment by weskerfoot** [comment]
Done

**Comment by weskerfoot** [comment]
Could still use work to add more information to the logs, but the basic architecture is down I think
