### ISSUE TITLE
Problem logging in

### ISSUE THREAD

**Issue by morris-of-orange** [weskerfoot/DeleteFB#66]
Whenever I run the program, it goes to Facebook, and enters the login information. I copy the email, and URL from a firefox window, and the password from my password manager. It then sends the Chrome window to: 
https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=110

where I reenter the same login credentials (copy-paste) and then it logs in correctly however by then, the program hits an error. 

I do not have 2FA enabled

Proposed solution:  If it hits this webpage, then check the url every few seconds, until the user inputs the email-password manually and hits login. after that continue running the program

On line 100 of login.py add:

`while Driver.getCurrentUrl()=="https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=110":`

`    time.sleep(5)`

**Comment by weskerfoot** [comment]
Are you getting a "Save Browser" screen? I think this might be the same issue as this https://github.com/weskerfoot/DeleteFB/issues/38

I can look at adding this check to the end of the login function, although I think it might be more robust to do something like:

```python
while "login/device-based/regular/login" in driver.getCurrentUrl():
    time.sleep(5)
```

That way it isn't depending on the exact query parameters being present.

Can you confirm this solves your issue?

Better yet, I might change the login function to go to this URL in the first place and avoid this issue, and the need to have a while loop.

**Comment by weskerfoot** [comment]
I'm going to try altering the login function to go to this page directly, which should hopefully avoid issues with logins.

It seems like https://github.com/weskerfoot/DeleteFB/issues/38 is a different issue which is going to be a bit more work to solve.

**Comment by weskerfoot** [comment]
Fixed in https://github.com/weskerfoot/DeleteFB/pull/67

**Comment by morris-of-orange** [comment]
This totally fixed it, thank you. Sorry I wasn't much of a help, I'm new to all this, so I couldn't be much help.

**Comment by weskerfoot** [comment]
Glad it solved your issue! No problem, and thanks for reporting it :)
