### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Sigri44** [weskerfoot/DeleteFB#69]
Hi,

I use virtual env, pip and requirements is good.

If i launch it, don't work : 
`python3.7 deletefb.py`
```python
Traceback (most recent call last):
  File "deletefb.py", line 2, in <module>
    from .tools.common import logger
ModuleNotFoundError: No module named '__main__.tools'; '__main__' is not a package
```

Thank you.

**Comment by weskerfoot** [comment]
Hi, give `python -m deletefb.deletefb` a try and run it from the root of the project. The code assumes it will be executed as a module.

**Comment by Sigri44** [comment]
Hi,

It's the same error.. :)

`~/DeleteFB/deletefb$ python3.7 -m deletefb.deletefb
Could not import runpy module
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 57, in <module>
    import types
  File "/home/sylvain/DeleteFB/deletefb/types.py", line 1, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
`

**Comment by weskerfoot** [comment]
> Hi,
> 
> It's the same error.. :)
> 
> ```python
> ~/DeleteFB/deletefb$ python3.7 -m deletefb.deletefb
> Could not import runpy module
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/runpy.py", line 14, in <module>
>     import importlib.machinery # importlib first so we can test #15386 via -m
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 57, in <module>
>     import types
>   File "/home/sylvain/DeleteFB/deletefb/types.py", line 1, in <module>
>     import attr
> ModuleNotFoundError: No module named 'attr'
> ```

This looks like an issue with your Python install, not this library, as far as I can tell.

Try installing it in a virtualenv, per the README, and see if you get the same error.

https://github.com/weskerfoot/DeleteFB#installation

**Comment by Sigri44** [comment]
> 
> 
> > Hi,
> > It's the same error.. :)
> > ```python
> > ~/DeleteFB/deletefb$ python3.7 -m deletefb.deletefb
> > Could not import runpy module
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.7/runpy.py", line 14, in <module>
> >     import importlib.machinery # importlib first so we can test #15386 via -m
> >   File "/usr/local/lib/python3.7/importlib/__init__.py", line 57, in <module>
> >     import types
> >   File "/home/sylvain/DeleteFB/deletefb/types.py", line 1, in <module>
> >     import attr
> > ModuleNotFoundError: No module named 'attr'
> > ```
> 
> This looks like an issue with your Python install, not this tool, as far as I can tell.
> 
> Try installing it with `pip3 install --user delete-facebook-posts` per the README, and see if you get the same issue.
> 
> https://github.com/weskerfoot/DeleteFB#installation

Hi !

Hi have always make this step, on my first message : 

```python

$:~/DeleteFB/deletefb$ python3.7 deletefb.py -E 'xxxx@xxxx.fr' -P 'xxxx' -U 'https://www.facebook.com/xxxx' -Y xxxx
Traceback (most recent call last):
  File "deletefb.py", line 2, in <module>
    from .tools.common import logger
ModuleNotFoundError: No module named '__main__.tools'; '__main__' is not a package
```

**Comment by weskerfoot** [comment]
@Sigri44 Try just `deletefb -E 'xxxx@xxxx.fr' -P 'xxxx' -U 'https://www.facebook.com/xxxx' -Y xxxx` instead. That should work if you have set up your `$PATH` variable correctly. 

If you're on a MacOS machine then see https://github.com/weskerfoot/DeleteFB/issues/70#issuecomment-505184943

**Comment by Sigri44** [comment]
Hey !

:/usr/local/bin is always in path, i don't undestand how de "deletefb" is recognized, this name not exist (juste deletefb.py), the pip install say "Requirement already satisfied".

`-bash: deletefb : commande introuvable`
