### ISSUE TITLE
bash: deletefb: command not found

### ISSUE THREAD

**Issue by xtremehume** [weskerfoot/DeleteFB#70]
deletefb script was installed on Mac 10.14.5 in `/Users/<USERNAME>/Library/Python/2.7/bin` I tried copying the deletefb script file to `~/.local/bin/deletefb` but that doesn't work either and I get

> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 562, in configure
>     handler = self.configure_handler(handlers[name])
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 735, in configure_handler
>     result = factory(**kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/handlers.py", line 434, in __init__
>     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1092, in __init__
>     StreamHandler.__init__(self, self._open())
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1121, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)
> PermissionError: [Errno 1] Operation not permitted: '/usr/deletefb.log'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/deletefb", line 11, in <module>
>     load_entry_point('delete-facebook-posts==1.1.7', 'console_scripts', 'deletefb')()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
>     return ep.load()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
>     return self.resolve()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/Users/[user]/Library/Python/3.7/lib/python/site-packages/deletefb/deletefb.py", line 4, in <module>
>     from .tools.likes import unlike_pages
>   File "/Users/[user]/Library/Python/3.7/lib/python/site-packages/deletefb/tools/likes.py", line 8, in <module>
>     LOG = logger(__name__)
>   File "/Users/[user]/Library/Python/3.7/lib/python/site-packages/deletefb/tools/common.py", line 45, in logger
>     logging.config.dictConfig(config["logging"])
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 799, in dictConfig
>     dictConfigClass(config).configure()
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/config.py", line 570, in configure
>     '%r' % name) from e

**Comment by weskerfoot** [comment]
Please see this https://stackoverflow.com/questions/22465332/setting-path-environment-variable-in-osx-permanently

Make sure `/Users/<USERNAME>/Library/Python/2.7/bin` is in your `$PATH`, then try running it again.

Copying won't work.

**Comment by weskerfoot** [comment]
Here are some more detailed instructions https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/#.Uydjga1dXDg

**Comment by weskerfoot** [comment]
@xtremehume Did altering your `$PATH` and then running the command as documented in the manual (i.e. `deletefb -E email -P password`) work?

**Comment by weskerfoot** [comment]
Closing, if there are still issues please comment

**Comment by wrapper** [comment]
Just an update, adding python to the path does work (OSX) but if you're using the current install you'll be using version 3.7: 

/Users/<USERNAME>/Library/Python/3.7/bin
