### ISSUE TITLE
Support to delete also all old private messages

### ISSUE THREAD

**Issue by mitar** [weskerfoot/DeleteFB#71]
There can be many of them and deleting them manually takes a long time.

I think the MVP could be simply deleting full conversations with anyone you have not talked since year X (so similar to timeline deletion, with `--year 2018` it would delete only full conversations which have been last updated in 2018).

A more interesting approach could be to delete only individual messages in all conversations for a given year. Not sure if one can delete also messages from the correspondent. I think that maybe deleting full conversation is then better.

**Comment by weskerfoot** [comment]
I think the simplest thing would be to just delete the entire conversation, as you say.

If I were going to do this feature I would probably just iterate through all your convos (not sure about archived ones, probably it would ignore those), and then remove the conversation.

As far as I know, unless you used the "private" mode where messages self-destruct, then there's no way to ensure the messages are removed from the recipient's copy.

**Comment by mitar** [comment]
I understand that it is not possible to really messages available to others, but I would like at least to hide them inside my own thread/conversation. So if somebody looks there nothing is visible on my side.

**Comment by weskerfoot** [comment]
I agree, I would find it useful as well. In fact I was thinking it could be useful to run it as a cronjob/timer periodically, to cull your conversation list. I'm going to look into ways I can improve the headless experience.

**Comment by weskerfoot** [comment]
Still a WIP. I ran into a bit of a blocker writing the code that gets the entire list of your conversations. Might be an easier way though.

**Comment by weskerfoot** [comment]
Found a nice way of doing it on the mobile site. Hopefully I'll have some time tonight to write it up and implement it.

**Comment by weskerfoot** [comment]
Made some progress. Switched to using the mobile site and now I can easily iterate through all conversations.

Still need to do:
- Archiving
- Filter by year
- Delete

**Comment by weskerfoot** [comment]
Basic features are implemented (getting a list of all convos, etc) and filtering by year is implemented.

I am going to implement a basic archiving feature and then add an option to delete them. Then this should be good enough to merge in.

**Comment by weskerfoot** [comment]
This is almost working, I just haven't had time to push it over the finish line

**Comment by weskerfoot** [comment]
@mitar This is now working in master. I will do a new release soon with updates to the documentation and so on.

https://github.com/weskerfoot/DeleteFB/pull/72

**Comment by mitar** [comment]
Awesome.
