### ISSUE TITLE
InvalidArgumentException raised during initial page load

### ISSUE THREAD

**Issue by ictheon** [weskerfoot/DeleteFB#77]
Installed through pip3 on Mint, this program worked perfectly for hours.  After doing a facebook official data backup, I consistently see the following error when calling with  -M wall -Y 2014

Traceback (most recent call last):
  File "/home/fshs/.local/bin/deletefb", line 11, in <module>
    sys.exit(run_delete())
  File "/home/fshs/.local/lib/python3.6/site-packages/deletefb/deletefb.py", line 110, in run_delete
    year=args.year
  File "/home/fshs/.local/lib/python3.6/site-packages/deletefb/tools/wall.py", line 27, in delete_posts
    driver.get(user_profile_url)
  File "/home/fshs/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/fshs/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/fshs/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=75.0.3770.90)

$ uname -a
Linux ------ 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ apt policy chromium-browser chromium-chromedriver python3 python3-pip
chromium-browser:
  Installed: 75.0.3770.90-0ubuntu0.18.04.1
  Candidate: 75.0.3770.142-0ubuntu0.18.04.1
  Version table:
     75.0.3770.142-0ubuntu0.18.04.1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
 *** 75.0.3770.90-0ubuntu0.18.04.1 100
        100 /var/lib/dpkg/status
     65.0.3325.181-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
chromium-chromedriver:
  Installed: 75.0.3770.142-0ubuntu0.18.04.1
  Candidate: 75.0.3770.142-0ubuntu0.18.04.1
  Version table:
 *** 75.0.3770.142-0ubuntu0.18.04.1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
        100 /var/lib/dpkg/status
     65.0.3325.181-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
python3:
  Installed: 3.6.7-1~18.04
  Candidate: 3.6.7-1~18.04
  Version table:
 *** 3.6.7-1~18.04 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.6.5-3 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
python3-pip:
  Installed: 9.0.1-2.3~ubuntu1.18.04.1
  Candidate: 9.0.1-2.3~ubuntu1.18.04.1
  Version table:
 *** 9.0.1-2.3~ubuntu1.18.04.1 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages
        100 /var/lib/dpkg/status
     9.0.1-2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages

**Comment by weskerfoot** [comment]
@ictheon Just to clarify, it logs in okay and then crashes when it gets to the stage where it should start deleting things? Are you passing the profile URL with a URL like `https://www.facebook.com/your.name` ?

**Comment by ictheon** [comment]
I was passing 'www.facebook.com/your.name'
Added the "https:// " string and it is working as expected.
My apologies. I assume this was right in front of my face somewhere.

**Comment by weskerfoot** [comment]
I could actually add some checks for that. I'll create another issue for
it. Glad you got it working.
