### ISSUE TITLE
Document and Fix CI

### ISSUE THREAD

**Issue by weskerfoot** [weskerfoot/DeleteFB#87]
https://travis-ci.org/weskerfoot/DeleteFB/builds/585078067?utm_source=github_status&utm_medium=notification

- The build needs registry credentials set up properly so it can build and push the images.
- Docs need an overhaul on how to run it in docker

**Comment by mmatoscom** [comment]
Hi, you need to head to https://travis-ci.org/weskerfoot/DeleteFB/settings
then fix var's values there as resgitry_pass, user, and image_name

**Comment by weskerfoot** [comment]
I updated the settings. We'll see if that fixes it.

**Comment by weskerfoot** [comment]
Seems like I got it to work
