### ISSUE TITLE
Support downloading while deleting

### ISSUE THREAD

**Issue by thinkingerrol** [weskerfoot/DeleteFB#9]
Would it make sense to support downloading while deleting? For me it would be kind of liberating.

**Comment by mimischi** [comment]
You can have Facebook prepare your data as an archive for download.

**Comment by weskerfoot** [comment]
Partially working in https://github.com/weskerfoot/DeleteFB/pull/31 but needs more work to make it log everything.

**Comment by weskerfoot** [comment]
Working in https://github.com/weskerfoot/DeleteFB/pull/31/commits/643929d3dd96048ef3e15d89d124f1f4293aa3a0
