### ISSUE TITLE
Automatically download the WebDriver for users instead of globally installing it.

### ISSUE THREAD

**Issue by esirK** [weskerfoot/DeleteFB#91]
While setting up the system on my machine, I am forced to Install the WebDriver globally  on my machine(`brew cask install chromedriver`). I think it would be better if we didn't have to install the driver but instead use the `executable_path` parameter `Chrome(executable_path=driver_path, options=options)` and download the driver locally to our project.
 I have implemented this on my machine and here is how it looks.

**Downloading the webdriver**
![Screenshot 2019-11-08 at 12 35 31](https://user-images.githubusercontent.com/13068580/68466121-ce36d680-0224-11ea-9b92-6bdca765a9d6.png)

**Location of the web driver.**
![Screenshot 2019-11-08 at 12 39 52](https://user-images.githubusercontent.com/13068580/68466153-e27ad380-0224-11ea-9fdd-56064eead547.png)

@weskerfoot  Kindly let me know if this is a feature we would want to have in the project. If so I will push my code and create a PR.

**Comment by weskerfoot** [comment]
This is a great idea. Is the binary statically linked? (i.e. will it work cross-platform?)

**Comment by esirK** [comment]
> This is a great idea. Is the binary statically linked? (i.e. will it work cross-platform?)

This is how I am achieving this 
```
        # Download it according to the current machine
        webdrivers = ['https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_mac64.zip',
                      'https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip',
                      'https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_win32.zip'
                      ]
        os_platform = platform.system()
        if os_platform == 'Darwin':
            chrome_webdriver = webdrivers[0]
        elif os_platform == 'Linux':
            chrome_webdriver = webdrivers[1]
        elif os_platform == 'Windows':
            chrome_webdriver = webdrivers[2]
        else:
            raise Exception("Unknown Operating system platform")
```
the extracted zip is then saved in the project file system.

**Comment by esirK** [comment]
I have created a PR for this. 
Here #92
