### ISSUE TITLE
Automate Execution blocked: Please navigate to https://www.facebook.com to continue

### ISSUE THREAD

**Issue by esirK** [weskerfoot/DeleteFB#93]
While I was working on a bug, I noticed that once a user is logged in, we check to see if the current url is `https://www.facebook.com/` and if it is not we block the execution until the user manualy navigates to `https://www.facebook.com/`. My suggestion would be we atleast try to do it for the user and if we fail after a retry we can ask the user to manually navigate to the URL.

#### Here is how I have done it on my branch.
If it is a feature we would love to have, I can create a PR for it. cc @weskerfoot 

<img width="851" alt="Screenshot 2019-11-09 at 15 56 41" src="https://user-images.githubusercontent.com/13068580/68528904-905fae00-0309-11ea-8ba3-91be611782b6.png">

**Comment by weskerfoot** [comment]
IIRC, this line
https://github.com/weskerfoot/DeleteFB/blob/b278d45ac721215fdff6cab160a3ec625e049782/deletefb/tools/login.py#L51

Should redirect to that URL, so the purpose of this code was to detect situations where e.g., Facebook is forcing them to do 2FA or some other verification, and the automatic 2FA stuff failed. I'll have to test it out to make sure it works as intended still if this code changes.

It could probably use better comments explaining how it's intended to work too

**Comment by esirK** [comment]
Thank you for the fast response.
I also thought it should redirect to that url but in my case, here is the URL that it redirects to 
`https://www.facebook.com/?sk=welcome` not sure if it's because my facebook account is new. But even if that is the case, it just shows that `driver.get("https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=110") ` doesn't guarantee to redirect to  `www.facebook.com`.

**Comment by weskerfoot** [comment]
Can anyone reproduce this behaviour?

**Comment by esirK** [comment]
I will close this if no one else can reproduce this.
