### ISSUE TITLE
Script can't find Chromedriver

### ISSUE THREAD

**Issue by nottavi** [weskerfoot/DeleteFB#95]
Hi,

I have installed your software with this method:

1. Install from PyPI with pip3 install --user delete-facebook-posts

As I am on Mac OS I've used the brew method to install chromedriver

I had to modify my PATH so I can execute the script

My password contains a "!" so I had to escape it.

The script seems to start but then I got this error message

Message: unknown error: cannot find Chrome binary

You need to install the chromedriver for Selenium

Please see this link https://github.com/weskerfoot/DeleteFB#how-to-use-it

I assume maybe a variable should be set or change so the script can find the location of chromedriver

Thank you

**Comment by esirK** [comment]
From this [PR](https://github.com/weskerfoot/DeleteFB/pull/92), the chrome driver will be automatically downloaded. I think the **how to use it** doc should be updated.

**Comment by nottavi** [comment]
Ok thank you I will have a look

**Comment by weskerfoot** [comment]
I haven't done a new release since that was merged so you have to install from github. I'll try and do a new release some time this week.

**Comment by weskerfoot** [comment]
v1.1.10 was released and the docs were updated to reflect the auto-install process. Hopefully that fixes it for you.

**Comment by weskerfoot** [comment]
I think we need to make the version configurable soon, otherwise I'm worried it might break when a new release of chrome breaks compatibility with the version of the chrome driver it installs.

**Comment by nottavi** [comment]
Did do what you mentionned

Executed the script
Got this:

Downloading Chrome Webdriver
100% |####################################################################################################################################|
DONE!
Traceback (most recent call last):
  File "/Users/nicolas/Library/Python/3.7/bin/deletefb", line 10, in <module>
    sys.exit(run_delete())
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/deletefb/deletefb.py", line 105, in run_delete
    two_factor_token=args.two_factor_token
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/deletefb/tools/login.py", line 41, in login
    driver = setup_selenium(driver_path, chrome_options)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/deletefb/tools/chrome_driver.py", line 52, in setup_selenium
    return webdriver.Chrome(executable_path=driver_path, options=options)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/nicolas/Library/Python/3.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

May be I am not installing the app correctly and globally ... Where should the chrome binary be ?

**Comment by weskerfoot** [comment]
Looks like an issue where it does not know the location of the chrome
binary. Similar to https://stackoverflow.com/a/46027522. I guess we need an
option to pass it as a parameter. You could clone the repo and modify it
manually like that answer suggests in the meantime I guess. Or try `brew
cask install google-chrome`.

**Comment by weskerfoot** [comment]
also this should be a new issue since it's different from the issue of the
chrome driver being not found

**Comment by weskerfoot** [comment]
I'm working on re-factoring this, as well as the chromedriver versioning stuff

**Comment by weskerfoot** [comment]
@nottavi This PR should fix it. https://github.com/weskerfoot/DeleteFB/pull/100

Install from source (check out the repo and do `cd DeleteFB; pip3 install --user .`) then pass `-B /path/to/google-chrome` for whatever the path to chrome is on your machine.

If you aren't sure then I'd suggest maybe doing `which google-chrome` or searching for it.

**Comment by nottavi** [comment]
Thanks @weskerfoot - it works

A great inspiration to do the same kind of script for Twitter.

**Comment by weskerfoot** [comment]
Thanks and I've actually looked into it for twitter but it's much more
difficult because of how twitter restricts things with the API and the
website. I know there are some tools that will do deletion though.
